### PR TITLE
fix for fastBPE install

### PR DESCRIPTION
**Pull request by ajkl**
picked from https://github.com/glample/fastBPE/blob/master/README.md#installation

### CODE REVIEW

**Comment by hoschwenk** [comment]
Hello,
Thanks for your pull request, but I believe that I fixed this already with an update some days ago.
Do you use the latest version of the code and still have problems installing fastBPE ?

**Comment by ajkl** [comment]
Yes, I tried the latest yesterday and the fastbpe install failed

**Comment by ajkl** [comment]
After this PR I also realized that the python wrapper for fastbpe is not installed in the install_external_tools script. Should that be added to the script? I did that manually as it was complaining when I used embed.

**Comment by Stolaine** [comment]
@ajkl are you able to run embed.sh? is yes can you give the steps to work around this issue?

**Comment by hoschwenk** [comment]
I just updated ./install_external_tools.sh, to correctly compile fastBPE. This was accidentally missing.

@ajkl . LASER does not automatically install python dependencies, but those are listed in the master README like FAISS, numpy, etc (so that people can chose how to handle this, e.g. a LASER specific environment etc)

@Stolaine just pull the latest version of LASER and everything should work.
As mentioned above, you need to do before your own "pip install .."

**Pull request closed without merging**
